backend/account/urls.py
from django.urls import path
from .views import *
from django.views.decorators.csrf import csrf_exempt

app_name = 'account'

urlpatterns = [
    path('', base, name='base'),
    path("api/login/", csrf_exempt(UserLoginAPI.as_view()), name="user_login_api"),
    path("api/simplelogin/", csrf_exempt(UserSimpleLoginAPI.as_view()), name="user_simple_login_api"),
    path("api/logout/", UserLogoutAPI.as_view(), name="user_logout_api"),
    path("api/register/", csrf_exempt(UserRegisterAPI.as_view()), name="user_register_api"),
    path("api/change_password/", UserChangePasswordAPI.as_view(), name="user_change_password_api"),
]

backend/dataprocess/urls.py
from django.urls.conf import path
from dataprocess.views import base
from dataprocess.views import (daily, platform, artist, artist_add, monitering, login)
from dataprocess import views
from django.views.decorators.csrf import csrf_exempt

app_name = "dataprocess"

urlpatterns = [
    path("", daily, name="base"),
    path("daily/", daily, name="daily"),
    path("platform/", platform, name="platform"),
    path("artist/", artist, name="artist"),
    path("artist/add/", artist_add, name="artist_add"),
    path("monitering/", monitering, name="monitering"),
    path("login/", login, name="login"),

    path('api/daily/', csrf_exempt(views.DataReportAPI.as_view()), name='datareport_api'),
    path('api/platform/', csrf_exempt(views.PlatformAPI.as_view()), name='platform_api'),
    path('api/artist/', csrf_exempt(views.ArtistAPI.as_view()), name='artist_api'),
    path('api/platform_of_artist/', csrf_exempt(views.PlatformOfArtistAPI.as_view()), name='platform_of_artist_api'),
    path('api/collect_target_item/', csrf_exempt(views.CollectTargetItemAPI.as_view()), name='collect_target_item_api'),
    path('api/platform_target_item/', csrf_exempt(views.PlatformTargetItemAPI.as_view()), name='platform_target_item_api'),
    path('api/schedule/', csrf_exempt(views.ScheduleAPI.as_view()), name='schedule_api'),
    path('api/crawler_error_table/', csrf_exempt(views.ResultQueryView.as_view()), name='crawler_error_table'),
]

backend/yg/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path("admin/", admin.site.urls),
    path("config/", include("config.urls")),
    path("dataprocess/", include("dataprocess.urls")),
    path("", include("account.urls")),
    path("crawler/", include("crawler.urls")),
]

backend/dataprocess/models.py
from django.db import models


class Platform(models.Model):
    name = models.TextField(unique=True)
    url = models.TextField()
    description = models.TextField(null=True, blank=True, default="")
    active = models.BooleanField(default=True)

    class Meta:
        db_table = "platform"


class ArtistProfile(models.Model):
    # More requirements is needed
    age = models.TextField(null=True)
    height = models.TextField(null=True)
    weight = models.TextField(null=True)

    class Meta:
        db_table = "artist_profile"


class Artist(models.Model):
    name = models.TextField(unique=True, max_length=100)
    level = models.TextField(max_length=10, default="S")
    gender = models.TextField(max_length=10, default="M")
    member_num = models.IntegerField(default=1)
    member_nationality = models.TextField(max_length=100, default="", blank=True)
    agency = models.TextField(null=True, default="", blank=True)
    image = models.ImageField(null=True)
    profile = models.OneToOneField(ArtistProfile, on_delete=models.CASCADE, null=True)
    debut_date = models.DateField(null=True)
    create_dt = models.DateTimeField(auto_now_add=True)
    update_dt = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        db_table = "artist"


class CollectTarget(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)  # if Artist is deleted, all of his/her data is removed
    platform = models.ForeignKey(Platform, on_delete=models.CASCADE)
    target_url = models.TextField(default="")
    target_url_2 = models.TextField(default="")
    channel = models.TextField(null=True)
    channel_name = models.TextField(null=True)
    sibling = models.BooleanField(default=False)
    create_dt = models.DateTimeField(auto_now_add=True)
    update_dt = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "collect_target"


class CollectData(models.Model):
    collect_target = models.ForeignKey(CollectTarget, on_delete=models.CASCADE)
    collect_items = models.JSONField(default=dict)

    class Meta:
        db_table = "collect_data"

backend/dataprocess/views.py
import os
from time import time
from django.contrib import auth
from django.shortcuts import render
from account.models import User
from dataprocess.models import CollectData
from config.models import PlatformTargetItem, CollectTargetItem, Schedule
from config.serializers import PlatformTargetItemSerializer, CollectTargetItemSerializer, ScheduleSerializer
from dataprocess.functions import export_datareport, import_datareport, import_collects, import_authinfo
from django.views.decorators.csrf import csrf_exempt
from .resources import *
from .serializers import *
from .models import *
from django.http.response import JsonResponse
from rest_framework.parsers import JSONParser
from rest_framework import status
from django.views.decorators.csrf import csrf_exempt
from utils.api import APIView
from django.shortcuts import render
from django.http import HttpResponse
import datetime
import openpyxl
from openpyxl.writer.excel import save_virtual_workbook
from .logger import userlogger

# login check using cookie
def logincheck(request):
    # 로그인 정보를 받기 위해 cookie사용
    username = request.COOKIES.get('username')
    if username is not None:
        if User.objects.filter(username=username).exists():
            # 이미 존재하는 username일때만 로그인
            user = User.objects.filter(username=username).first()
            auth.login(request, user)
    return request

# Create your views here.
def base(request):
    '''
    general page
    '''
    platforms = Platform.objects.all() #get all platform info from db
    values = {
        'first_depth' : '데이터 리포트',
        'second_depth': '일별 리포트',
        'platforms': platforms
    }
    request = logincheck(request)
    return render(request, 'dataprocess/daily.html',values)
    
@csrf_exempt
def daily(request):
    if request.method == 'GET':
        '''
        general page
        '''
        platforms = Platform.objects.all() #get all platform info from db
        values = {
            'first_depth' : '데이터 리포트',
            'second_depth': '일별 리포트',
            'platforms': platforms
        }
        request = logincheck(request)
        return render(request, 'dataprocess/daily.html',values)
    else:
        type = request.POST['type']
        if type == 'import':
            '''
            import from excel
            '''
            platforms = Platform.objects.all()  # get all platform info from db
            if not 'importData' in request.FILES:
                values = {
                    'first_depth' : '데이터 리포트',
                    'second_depth': '일별 리포트',
                    'platforms': platforms,
                    'alert': '파일을 첨부해주세요.'
                    }
                request = logincheck(request)
                return render(request, 'dataprocess/daily.html', values)
            import_file = request.FILES['importData']            
            excel_import_date = request.POST.get('excel_import_date', None)  # 0000-0-0 형태

            wb = openpyxl.load_workbook(import_file)
            sheets = wb.sheetnames
            worksheet = wb[sheets[0]]
            import_datareport(worksheet, excel_import_date)

            values = {
                'first_depth' : '데이터 리포트',
                'second_depth': '일별 리포트',
                'platforms': platforms,
                'alert': '저장되었습니다.'
                }
            request = logincheck(request)
            return render(request, 'dataprocess/daily.html',values)
        elif type == 'export':
            '''
            export to excel
            '''
            excel_export_type = request.POST.get('excel_export_days', None) # 누적 or 기간별
            excel_export_start_date = request.POST.get('excel_export_start_date', None) # 0000-0-0 형태
            excel_export_end_date = request.POST.get('excel_export_end_date', None) # 0000-0-0 형태
            book = export_datareport(excel_export_type, excel_export_start_date, excel_export_end_date)
            if excel_export_type == '누적':
                filename = "datareport %s.xlsx" % (excel_export_start_date)
            elif excel_export_type == '기간별':
                filename = "datareport기간별 %s~%s.xlsx" % (excel_export_start_date,excel_export_end_date)
            response = HttpResponse(content=save_virtual_workbook(book), content_type='application/vnd.ms-excel')
            response['Content-Disposition'] = 'attachment; filename='+filename
            return response
        elif type == 'import2':
            '''
            import2 from excel (collect_target_item, artist, platform)
            '''
            platforms = Platform.objects.all()  # get all platform info from db
            if not 'importData' in request.FILES:
                values = {
                    'first_depth' : '데이터 리포트',
                    'second_depth': '일별 리포트',
                    'platforms': platforms,
                    'alert': '파일을 첨부해주세요.'
                    }
                request = logincheck(request)
                return render(request, 'dataprocess/daily.html', values)
            import_file = request.FILES['importData']
            wb = openpyxl.load_workbook(import_file)
            sheets = wb.sheetnames
            worksheet = wb[sheets[0]]
            import_collects(worksheet)
            values = {
                'first_depth' : '데이터 리포트',
                'second_depth': '일별 리포트',
                'platforms': platforms,
                'alert': '저장되었습니다.'
                }
            request = logincheck(request)
            return render(request, 'dataprocess/daily.html',values)
        elif type == 'import3':
            '''
            import3 from excel (auth_info)
            '''
            platforms = Platform.objects.all()  # get all platform info from db
            if not 'importData' in request.FILES:
                values = {
                    'first_depth' : '데이터 리포트',
                    'second_depth': '일별 리포트',
                    'platforms': platforms,
                    'alert': '파일을 첨부해주세요.'
                    }
                request = logincheck(request)
                return render(request, 'dataprocess/daily.html', values)
            import_file = request.FILES['importData']
            wb = openpyxl.load_workbook(import_file)
            sheets = wb.sheetnames
            worksheet = wb[sheets[0]]
            import_authinfo(worksheet)
            values = {
                'first_depth' : '데이터 리포트',
                'second_depth': '일별 리포트',
                'platforms': platforms,
                'alert': '저장되었습니다.'
                }
            request = logincheck(request)
            return render(request, 'dataprocess/daily.html',values)
    
def platform(request):
     '''
     general page
     '''
     values = {
        'first_depth' : '플랫폼 관리',
        'second_depth': '플랫폼 관리'
    }
     request = logincheck(request)
     return render(request, 'dataprocess/platform.html',values)

def artist(request):
    artists = Artist.objects.all()
    values = {
      'first_depth' : '아티스트 관리',
      'second_depth': '데이터 URL 관리',
      'artists': artists
    }
    request = logincheck(request)
    return render(request, 'dataprocess/artist.html',values)

@csrf_exempt
def artist_add(request):
    platforms = Platform.objects.all()
    values = {
      'first_depth' : '아티스트 관리',
      'second_depth': '데이터 URL 관리',
      'platforms' : platforms
    }
    request = logincheck(request)
    return render(request, 'dataprocess/artist_add.html',values)

def login(request):
    values = {
      'first_depth' : '로그인'
    }
    request = logincheck(request)
    return render(request, 'dataprocess/login.html',values)


class PlatformAPI(APIView):
    # @login_required
    def get(self, request):
        '''
        Platform read api
        '''
        try:
            platform_objects = Platform.objects.all()
            if platform_objects.exists():
                platform_objects_values = platform_objects.values()
                platform_datas = []
                for platform_value in platform_objects_values:
                    platform_datas.append(platform_value)
                return JsonResponse(data={'success': True, 'data': platform_datas})
            else:
                return JsonResponse(data={'success': True, 'data': []})
        except:
            return JsonResponse(status=400, data={'success': False})

    # @login_required
    def post(self, request):
        '''
        Platform create api
        '''
        try:
            platform_object = JSONParser().parse(request)
            platform_serializer = PlatformSerializer(data=platform_object)
            if platform_serializer.is_valid():
                # 1. platform 생성
                platform_serializer.save()

                #특정 아티스트 전용 collect_target 생성 시 사용할 코드
                # 2. 현재 존재하는 모든 artist에 대해 collect_target 생성 -> platform과 연결
                artist_objects = Artist.objects.all()
                artist_objects_values = artist_objects.values()
                for artist_objects_value in artist_objects_values:
                    collecttarget = CollectTarget(
                        platform_id = platform_serializer.data['id'],
                        artist_id = artist_objects_value['id']
                        )
                    collecttarget.save()
                    #3. 해당 collecttarget에 대한 schedule 생성
                    schedule_object = Schedule.objects.filter(collect_target_id = collecttarget.id).first()
                    schedule_data = {
                            'collect_target': collecttarget.id,
                            'schedule_type': 'daily',
                            'active': True,
                            'execute_time': datetime.time(9,0,0)
                        }
                    schedule_serializer = ScheduleSerializer(schedule_object, data=schedule_data)
                    if schedule_serializer.is_valid():
                        schedule_serializer.save()

backend/dataprocess/templates/dataprocess/artist.html
<!DOCTYPE html>
<html lang="ko">
    {% extends 'main.html' %}
    
    {% block content %}

    <script>
        function go_to_artist_add(){
            location.href = "{% url 'dataprocess:artist_add' %}";
        }
    </script>
   <div class="forms">
    <div class="contents">
        <table class="resizeable">
            <thead>
                <tr class="resizeable">
                    <th class="resizeable">
                        <div class="resiazable_column">
                            <div class="no-margin-button-layout">
                                <button onclick=go_to_artist_add() class="btn btn-primary border-0"
                                     style="font-size: 10px !important; font-weight: bold;">추가</button>
                                <button id="save-artists" class="btn btn-primary border-0"
                                    style="font-size: 10px !important; font-weight: bold;">저장</button>
                            </div>
                            <span class="artist-title" style="display: hidden; color:transparent; margin-bottom: 36px;">hidden</span>
                             <table id="artist-table" class="table table-centered table-nowrap mb-0 rounded input-transparent">
                                 <thead id="artist-header" class="thead-dark">
                                     <tr>
                                         <td class="hidden">id</td>
                                         <td>ARTIST</td>
                                         <td class="artist_hidden">구분</td>
                                         <td class="artist_hidden">성별</td>
                                         <td class="artist_hidden">맴버 수</td>
                                         <td class="artist_hidden">국적</td>
                                         <td class="artist_hidden">기획사</td>
                                         <td class="artist_hidden">데뷔</td>
                                         <td class="artist_hidden">사용</td>
                                     </tr>
                                 </thead>
                                 <tbody id="artist-body">
                                     {% if artists %}
                                     {% for artist in artists %}
                                     <tr>
                                         <td class="hidden"><input type="text" value={{artist.id}}></input></td>
                                         <td>
                                             <input type="button" name="artist-name" title="{{artist.name}}" 
                                             value="{{artist.name}}" class="input-btn"> </input>
                                        </td>
                                         <td class="artist_hidden">
                                             <input type="text" style="width:100%" title={{artist.level}} value={{artist.level}}></input>
                                        </td>
                                         <td class="artist_hidden">
                                             <input type="text" style="width:100%" title={{artist.gender}} value={{artist.gender}}></input>
                                        </td>
                                         <td class="artist_hidden">
                                             <input type="text" style="width:100%" title={{artist.member_num}} value={{artist.member_num}}></input>
                                        </td>
                                         <td class="artist_hidden">
                                             <input type="text" style="width:100%" title="{{artist.member_nationality}}" value={{artist.member_nationality}}></input>
                                        </td>
                                         <td class="artist_hidden">
                                             <input type="text" style="width:100%" title="{{artist.agency}}" value={{artist.agency}}></input>
                                        </td>
                                         <td class="artist_hidden">
                                             <input type="text" style="width:100%" title="{{artist.debut_date|date:"Y-m-d"}}" value={{artist.debut_date|date:"Y-m-d"}}></input>
                                        </td>
                                         {% if artist.active %}
                                             <td class="artist_hidden"><input checked type="checkbox"></input></td>
                                         {% else %}
                                             <td class="artist_hidden"><input type="checkbox"></input></td>
                                         {% endif %}
                                     </tr>
                                     {% endfor %}
                                     {% else %}
                                     {% endif %}
                                 </tbody>
                             </table>
                             <button class="border-0 expand" id="artist_open_btn">
                                 <i class="fas fa-chevron-left" id="artist_open"></i>
                            </button>
                         </div>
                    </th>

                    <th class="resizeable">
                        <div class="resiazable_column">
                            <div class="no-margin-button-layout">
                                <button id="save-artists-platform" class="btn btn-primary border-0"
                                style="font-size: 10px !important; font-weight: bold;">저장</button>
                            </div>
                            <span class="artist-title" id="artist-subtitle" style="color: transparent; margin-bottom: 36px;">hidden</span>
                            <table id="artist-table" class="table table-centered table-nowrap mb-0 rounded input-transparent">
                                <thead id="artist-header" class="thead-dark">
                                    <tr>
                                        <td class="hidden">artist_id</td>
                                        <td class="hidden">platform_id</td>
                                        <td class="hidden">id</td>
                                        <td>PLATFORM</td>
                                        <td class="platform_hidden">URL 1</td>
                                        <td class="platform_hidden">URL 2</td>
                                    </tr>
                                </thead>
                                <tbody id="artist-body-platform"></tbody>
                            </table>
                            <button class="border-0 expand" id="platform_open_btn">
                                <i class="fas fa-chevron-left" id="platform_open"></i>
                           </button>
                        </div>
                    </th>

                    <th class="resizeable">
                        <div class="resiazable_column">
                            <div class="no-margin-button-layout">
                                <button id="save-list" class="btn btn-primary border-0"
                                style="font-size: 10px !important; font-weight: bold;">저장</button>
                            </div>
                            <span class="artist-title" id="platform-subtitle" style="color: transparent;">플랫폼</span>
                            <div class="artist_attr_button_layout">
                                <button id="artist_attr_add_button"> + </button>
                            </div>
                            <table id="artist-table" class="table table-centered table-nowrap mb-0 rounded input-transparent">
                                <thead id="artist-header" class="thead-dark">
                                    <tr>
                                        <td class="hidden">id</td>
                                        <td>조사항목</td>
                                        <td>내용</td>
                                        <td class="item_hidden">xpath</td>
                                        <td class="item_hidden">삭제</td>
                                    </tr>
                                </thead>
                                <tbody id="artist-body-list">

                                </tbody>
                            </table>
                            <button class="border-0 expand" id="item_open_btn">
                                <i class="fas fa-chevron-left" id="item_open"></i>
                           </button>
                        </div>
                    </th>
                </tr>
            </thead>
        </table>

     </div>
   </div>
    

    {% endblock content %}
</html>

backend/dataprocess/templates/dataprocess/artist_add.html
<!DOCTYPE html>
<html lang="ko">
    {% extends 'main.html' %}
    
    {% block content %}

    <script>
        function go_to_artist2(){
            location.href = "{% url 'dataprocess:artist' %}";
        }
     </script>
    
    <div class="forms">
        <form method="POST" class="add-form">
           <div class="row_layout flexstart_layout" style="margin-bottom: 10px;">
                <a href="{% url 'dataprocess:artist' %}" class="btn btn-primary border-0"
                style="font-size: 10px !important; text-decoration-line: none;font-weight: bold; margin-right: 5px;">
                    취소
                </a>
                <!-- <button class="excel-btn" onclick=go_to_artist2()>취소</button> -->
                <button class="btn btn-primary border-0" id="add-submit" style="font-size: 10px !important; font-weight: bold;">저장</button>
            </div>
            <div class="row_layout flexstart_layout">
                <table class="table table-centered table-nowrap mb-0 rounded input-transparent
                left-bold">
                    <thead class="thead-dark" style="text-align: center !important;">
                        <tr>
                            <th class="border-0 title-th">항목</th>
                            <th class="border-0 title-th">내용</th>
                        </tr>
                    </thead>
                
                    <tbody>
                        <tr>
                            <th>아티스트명</th>
                            <td><input class="add-target-input"  type="text" placeholder="blackpink"/></td>
                        </tr>
                        <tr>
                            <th>구분</th>
                            <td><input class="add-target-input"  type="text" placeholder="S/A/B/.." /></td>
                        </tr> <tr>
                            <th>성별</th>
                            <td><input class="add-target-input"  type="text" placeholder="M/F" /></td>
                        </tr> <tr>
                            <th>맴버</th>
                            <td><input class="add-target-input"  type="text" placeholder="맴버 수" /></td>
                        </tr> <tr>
                            <th>국적</th>
                            <td><input class="add-target-input"  type="text" placeholder="대한민국 4, 미국 1.." /></td>
                        </tr> 
                        <tr>
                            <th>기획사</th>
                            <td><input class="add-target-input"  type="text" placeholder="기획사" /></td>
                        </tr>
                        <tr>
                            <th>데뷔일</th>
                            <td><input class="add-target-input"  type="text" placeholder="2001-1-1" /></td>
                        </tr>
                    </tbody>
                </table>

               <table class="add-table table table-centered table-nowrap mb-0 rounded input-transparent
               left-bold">
                   <thead id="url-header" class="thead-dark">
                       <th class="border-0 title-th">플랫폼</th>
                       <th class="border-0 title-th">데이터 수집 URL</th>
                   </thead>
                   <tbody id="artist-urls">
                  {% if platforms %}
                   {% for platform in platforms %}
                   <tr>
                        <td style="text-align: center;">{{platform.name}}</td>
                        <td style="display: flex;">
                            <input class="add-target-input-1"  type="text" placeholder="URL" />
                            <span id="url_add_button"> + </span>
                            <span id="url_delete_button"> - </span>
                        </td>
                    </tr>
                   {% endfor %}
                  {% else %}
                  {% endif %}
                </tbody>
               </table>
            </div>
        


        </form>
    </div>
    {% endblock content %}
</html>

backend/dataprocess/templates/dataprocess/error_report.html
<div class="card-body">
    <table class="table table-centered table-nowrap mb-0 rounded error-report-table">
        <thead class="thead-dark">
            <tr>
                <th>오류</th>
                <th>아티스트</th>
                <th>플랫폼</th>
                <th>URL</th>
                <th class="hidden">id</th>
                <th style="color: black">저장</th>
            </tr>
        </thead>
        <tbody id="error-report">
        </tbody>
    </table>
    <nav aria-label="Page navigation example" style="margin-top: 12px;" >
        <ul class="pagination justify-content-center">
          
        </ul>
      </nav>
</div>

backend/dataprocess/templates/dataprocess/hourly_artist.html
<div class="modal fade" id="modal-default" tabindex="-1" aria-labelledby="modal-default" aria-modal="true" role="dialog" style="display: none;">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="h6 modal-title" id="schedule-modal-title" style="font-weight: bold;"> 플랫폼의 시간별 아티스트 </h2>
                <h2 class="hidden" id="schedule-platform-index">0</h2>
            </div>
            <div class="modal-body">
                <div id="hourly-artist" style="text-align: left;">

                </div>
                
                
            </div>
            <div class="modal-footer">
                <button id="schedule-close" type="button" class="btn btn-link text-gray-600 ms-auto" data-bs-dismiss="modal">닫기</button>
            </div>
        </div>
    </div>
</div>

backend/dataprocess/templates/dataprocess/login.html
<!DOCTYPE html>
<html lang="ko">

   {% extends 'main.html' %}

   {% block content %}

   <script>
      function go_to_login(){
          location.href = "{% url 'account:user_simple_login_api' %}";
      }
   </script>

   <!-- 로그인 -->
   <div class="forms">
      <button class="excel-btn" id="login-btn" onclick=go_to_login()>
         로그인
      </button>
   </div>

   {% endblock content %}

</html>

backend/dataprocess/templates/dataprocess/main.html
<!DOCTYPE html>
<html lang="ko">
   {% extends "main.html" %}

   {% block content %}

   <script>
      function go_to_login(){
          location.href = "{% url 'account:user_simple_login_api' %}";
      }
      function go_to_datareport(){
          location.href = "{% url 'dataprocess:daily' %}";
      }
      function go_to_platform(){
          location.href = "{% url 'dataprocess:platform' %}";
      }
      function go_to_artist(){
          location.href = "{% url 'dataprocess:artist' %}";
      }
      function go_to_monitering(){
          location.href = "{% url 'dataprocess:monitering' %}";
      }
   </script>

   <!-- 로그인 -->
   {% if user.is_authenticated %}
   <div class="forms">
      <br>
      <br>
      <div class="column_layout" style="width: 30%;">
         <button class="btn btn-primary border-0" style="font-size: 12px; font-weight: bold;" id="login-btn" onclick=go_to_datareport()>
            데이터리포트로 이동
         </button>
         <button class="btn btn-primary border-0" style="font-size: 12px; font-weight: bold;" onclick=go_to_platform()>
            플랫폼 관리로 이동
         </button>
         <button class="btn btn-primary border-0" style="font-size: 12px; font-weight: bold;" onclick=go_to_artist()>
            아티스트 관리로 이동
         </button>
         <button class="btn btn-primary border-0" style="font-size: 12px; font-weight: bold;" onclick=go_to_monitering()>
            모니터링 관리로 이동
         </button>
      </div>
   </div>
    {% else %}
    <div class="forms">
      <button class="btn btn-primary border-0" style="font-size: 12px; font-weight: bold; width: 100px;"
      id="login-btn" onclick=go_to_login()>
         로그인
      </button>
   </div>
    {% endif %}

   {% endblock content %}
</html>