backend/account/urls.py
from django.urls import path
from .views import *
from django.views.decorators.csrf import csrf_exempt

app_name = 'account'

urlpatterns = [
    path('', base, name='base'),
    path("api/login/", csrf_exempt(UserLoginAPI.as_view()), name="user_login_api"),
    path("api/simplelogin/", csrf_exempt(UserSimpleLoginAPI.as_view()), name="user_simple_login_api"),
    path("api/logout/", UserLogoutAPI.as_view(), name="user_logout_api"),
    path("api/register/", csrf_exempt(UserRegisterAPI.as_view()), name="user_register_api"),
    path("api/change_password/", UserChangePasswordAPI.as_view(), name="user_change_password_api"),
]

backend/dataprocess/urls.py
from django.urls.conf import path
from dataprocess.views import base
from dataprocess.views import (daily, platform, artist, artist_add, monitering, login)
from dataprocess import views
from django.views.decorators.csrf import csrf_exempt

app_name = "dataprocess"

urlpatterns = [
    path("", daily, name="base"),
    path("daily/", daily, name="daily"),
    path("platform/", platform, name="platform"),
    path("artist/", artist, name="artist"),
    path("artist/add/", artist_add, name="artist_add"),
    path("monitering/", monitering, name="monitering"),
    path("login/", login, name="login"),

    path('api/daily/', csrf_exempt(views.DataReportAPI.as_view()), name='datareport_api'),
    path('api/platform/', csrf_exempt(views.PlatformAPI.as_view()), name='platform_api'),
    path('api/artist/', csrf_exempt(views.ArtistAPI.as_view()), name='artist_api'),
    path('api/platform_of_artist/', csrf_exempt(views.PlatformOfArtistAPI.as_view()), name='platform_of_artist_api'),
    path('api/collect_target_item/', csrf_exempt(views.CollectTargetItemAPI.as_view()), name='collect_target_item_api'),
    path('api/platform_target_item/', csrf_exempt(views.PlatformTargetItemAPI.as_view()), name='platform_target_item_api'),
    path('api/schedule/', csrf_exempt(views.ScheduleAPI.as_view()), name='schedule_api'),
    path('api/crawler_error_table/', csrf_exempt(views.ResultQueryView.as_view()), name='crawler_error_table'),
]

backend/yg/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path("admin/", admin.site.urls),
    path("config/", include("config.urls")),
    path("dataprocess/", include("dataprocess.urls")),
    path("", include("account.urls")),
    path("crawler/", include("crawler.urls")),
]

backend/templates/head.html
{% load static %}
<head>
    <meta charset="UTF-8" />
    <title>YG entertainment</title>

    <!-- bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    
    <!-- GOOGLE FONTS LINK -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
    <link href="https://fonts.googleapis.com/css2?family= Titillium+Web:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap" rel="stylesheet">

    <!-- DEFAULT CSS LINK -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/socialblade.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/platform.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/artist.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/monitering.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/resizable-table-columns.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/volt.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/volt.css.map' %}"/>

    <!--Font Awesome-->
    <script src="https://use.fontawesome.com/releases/v5.2.0/js/all.js"></script>

    <!-- JS selection -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" defer></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js" defer></script>


     <!-- DATATABLE LINK -->
     <link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css"/> 
     <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js" defer></script>

    <!-- JS LINK -->
    <script src="{% static 'js/socialblade.js' %}" defer></script>
    <script src="{% static 'js/base.js' %}" defer></script>
    <script src="{% static 'js/dataReport.js' %}" defer></script>
    <script src="{% static 'js/platform.js' %}" defer></script>
    <script src="{% static 'js/artist.js' %}" defer></script>
    <script src="{% static 'js/monitering.js' %}" defer></script>
    <script src="{% static 'js/crawler_error.js' %}" defer></script>
    <script src="{% static 'js/resizable-table-columns.js' %}" defer></script>


</head>

backend/templates/header.html
<header class="header">
    <script>
        function go_to_main(){
          location.href = "{% url 'account:base' %}";
      }
    </script>
   {% if first_depth and second_depth %}
   <div class="header-element">
        <span onclick="go_to_main()" class="first-depth"><svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path></svg></span>
        <span class="middle-1"><i class="fas fa-chevron-right"></i></span></span>
        <span class="second-depth">{{ first_depth }}</span>
        <span class="middle-2"><i class="fas fa-chevron-right"></i></span></span>
        <span class="third-depth">{{ second_depth }}</span>
    </div>
   {% elif first_depth and not second_depth %}
    <div class="header-element">
        <span onclick="go_to_main()" class="first-depth"><svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path></svg></span>
        <span class="middle-1"><i class="fas fa-chevron-right"></i></span></span>
        <span class="second-depth">{{ first_depth }}</span>
        <span class="middle-2"></span></span>
        <span class="third-depth"></span>
    </div>
   {% else %}
   <div class="header-element">
        <span onclick="go_to_main()" class="first-depth"><svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path></svg></span>
        <span class="middle-1"></span>
        <span class="second-depth"></span>
        <span class="middle-2"></span>
        <span class="third-depth"></span>
    </div>
   {% endif %}

   <script>
        function go_to_logout(){
            location.href = "{% url 'account:user_logout_api' %}";
        }
        function go_to_login(){
            location.href = "{% url 'account:user_simple_login_api' %}";
        }
   </script>

   {% if user.is_authenticated %}
   <button style="line-height: 0;" class="logout-btn btn btn-sm btn-gray-800" id="logout-btn" onclick=go_to_logout()>
        로그아웃
    </button>
    {% else %}
    <button style="line-height: 0;" class="login-btn btn btn-sm btn-gray-800" id="login-btn" onclick=go_to_login()>
        로그인
    </button>
    {% endif %}
</header>

backend/templates/main.html
<!DOCTYPE html>
<html lang="ko">
    {% include 'head.html' %}

    {% include 'sidebar.html' %}

    {% include 'header.html' %}

    {% block content %}
       
   {% endblock content %}

</html>

backend/templates/sidebar.html
<nav style="max-width: 220px;" id="sidebarMenu" class="sidebar d-lg-block bg-gray-800 text-white collapse" data-simplebar>
    <div class="sidebar-inner px-4 pt-3" style="margin-top: 150px;">
      <ul class="nav flex-column pt-3 pt-md-0">
        <li class="nav-item">
          <a href="{% url 'account:base' %}" class="nav-link d-flex align-items-center">
            <span class="sidebar-icon">
                <svg style="width: 20px; height:20px;" class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path></svg>
            </span>
            <span class="mt-1 ms-1 sidebar-text">처음 페이지</span>
          </a>
        </li>
        <li class="nav-item">
          <span
            class="nav-link  collapsed  d-flex justify-content-between align-items-center data-report"
            data-bs-toggle="collapse" data-bs-target="#submenu-app">
            <span>
              <span class="sidebar-icon">
                <svg style="width: 20px; height:20px;" class="icon" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 3a1 1 0 000 2v8a2 2 0 002 2h2.586l-1.293 1.293a1 1 0 101.414 1.414L10 15.414l2.293 2.293a1 1 0 001.414-1.414L12.414 15H15a2 2 0 002-2V5a1 1 0 100-2H3zm11.707 4.707a1 1 0 00-1.414-1.414L10 9.586 8.707 8.293a1 1 0 00-1.414 0l-2 2a1 1 0 101.414 1.414L8 10.414l1.293 1.293a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path></svg>
              </span> 
              <span class="sidebar-text">데이터 리포트</span>
            </span>
            <span class="link-arrow">
              <svg class="icon icon-sm" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg>
            </span>
          </span>
          <div class="multi-level collapse data-report-in"
            role="list" id="submenu-app" aria-expanded="false">
            <ul class="flex-column nav">
              <li class="nav-item ">
                <a class="nav-link" href="{% url 'dataprocess:daily' %}">
                  <span class="sidebar-text sidebar-text-inner">일별 리포트</span>
                </a>
                <a class="nav-link" href="#">
                  <span class="sidebar-text sidebar-text-inner">시간별 리포트</span>
                </a>
              </li>
            </ul>
          </div>
        </li>
          <li class="nav-item">
            <span
              class="nav-link  collapsed  d-flex justify-content-between align-items-center platforms-m"
              data-bs-toggle="collapse" data-bs-target="#submenu-app">
              <span>
                <span class="sidebar-icon">
                  <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5 4a3 3 0 00-3 3v6a3 3 0 003 3h10a3 3 0 003-3V7a3 3 0 00-3-3H5zm-1 9v-1h5v2H5a1 1 0 01-1-1zm7 1h4a1 1 0 001-1v-1h-5v2zm0-4h5V8h-5v2zM9 8H4v2h5V8z" clip-rule="evenodd"></path></svg>
                </span> 
                <span class="sidebar-text">플랫폼 관리</span>
              </span>
              <span class="link-arrow">
                <svg class="icon icon-sm" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg>
              </span>
            </span>
            <div class="multi-level collapse platform-in"
              role="list" id="submenu-app" aria-expanded="false">
              <ul class="flex-column nav">
                <li class="nav-item ">
                  <a class="nav-link" href="{% url 'dataprocess:platform' %}">
                    <span class="sidebar-text sidebar-text-inner">플랫폼 관리</span>
                  </a>
                </li>
              </ul>
            </div>
          </li>
          <li class="nav-item">
            <span
              class="nav-link  collapsed  d-flex justify-content-between align-items-center artists-m"
              data-bs-toggle="collapse" data-bs-target="#submenu-app">
              <span>
                <span class="sidebar-icon">
                    <i class="fas fa-user-edit" style="margin-top: 5px; height: 20px; width: 20px;"></i>
                </span> 
                <span class="sidebar-text">아티스트 관리</span>
              </span>
              <span class="link-arrow">
                <svg class="icon icon-sm" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg>
              </span>
            </span>
            <div class="multi-level collapse artist-in"
              role="list" id="submenu-app" aria-expanded="false">
              <ul class="flex-column nav">
                <li class="nav-item ">
                  <a class="nav-link" href="{% url 'dataprocess:artist' %}">
                    <span class="sidebar-text sidebar-text-inner">데이터 URL 관리</span>
                  </a>
                </li>
              </ul>
            </div>
          </li>
          <li class="nav-item">
            <span
              class="nav-link  collapsed  d-flex justify-content-between align-items-center monitering-m"
              data-bs-toggle="collapse" data-bs-target="#submenu-app">
              <span>
                <span class="sidebar-icon">
                    <svg style="width:20px; height:20px;" class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M11.49 3.17c-.38-1.56-2.6-1.56-2.98 0a1.532 1.532 0 01-2.286.948c-1.372-.836-2.942.734-2.106 2.106.54.886.061 2.042-.947 2.287-1.561.379-1.561 2.6 0 2.978a1.532 1.532 0 01.947 2.287c-.836 1.372.734 2.942 2.106 2.106a1.532 1.532 0 012.287.947c.379 1.561 2.6 1.561 2.978 0a1.533 1.533 0 012.287-.947c1.372.836 2.942-.734 2.106-2.106a1.533 1.533 0 01.947-2.287c1.561-.379 1.561-2.6 0-2.978a1.532 1.532 0 01-.947-2.287c.836-1.372-.734-2.942-2.106-2.106a1.532 1.532 0 01-2.287-.947zM10 13a3 3 0 100-6 3 3 0 000 6z" clip-rule="evenodd"></path></svg>
                </span> 
                <span class="sidebar-text">모니터링 관리</span>
              </span>
              <span class="link-arrow">
                <svg class="icon icon-sm" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg>
              </span>
            </span>
            <div class="multi-level collapse monitering-in"
              role="list" id="submenu-app" aria-expanded="false">
              <ul class="flex-column nav">
                <li class="nav-item ">
                  <a class="nav-link" href="{% url 'dataprocess:monitering' %}">
                    <span class="sidebar-text sidebar-text-inner">모니터링</span>
                  </a>
                </li>
              </ul>
            </div>
          </li>
      </ul>
    </div>
  </nav>
  <button class="sidebar-btn btn-gray-800"><span><i class="fas fa-chevron-left"></i></span></button>
      